CREATE TABLE address (
    id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    number VARCHAR(10) DEFAULT NULL,
    complement VARCHAR(30) DEFAULT NULL,
    street VARCHAR(50) DEFAULT NULL,
    district VARCHAR(50) DEFAULT NULL,
    city VARCHAR(50) DEFAULT NULL,
    state VARCHAR(50) DEFAULT NULL,
    country VARCHAR(50) DEFAULT NULL,
    deleted_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)